# File: /Framework/agents/corrective_action_agent.py
import importlib
import inspect
import json
import logging
import os
import re
import sys
import traceback
from pathlib import Path
from typing import Any, Dict, List, Optional
import json
import asyncio
from contextlib import AsyncExitStack  # Added for direct MCP session management

from autogen import ConversableAgent
from openai import OpenAI
from rich.console import Console
from rich.live import Live
from rich.markdown import Markdown
from rich.panel import Panel
from rich.spinner import Spinner

# MCP library imports for direct communication
# Assuming this is the correct import for ClientSession
from mcp import ClientSession

# Assuming this is the correct import for sse_client
from mcp.client.sse import sse_client

# Assuming mcp.types might be needed for type hints or constants
import mcp.types as types

from ..config import Config
from .prompts.revised_prompt import SystemPrompts

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# %%


class LLM_Agent(ConversableAgent):
    def __init__(self, mcp_server_url: str = "http://localhost:3002/sse"):
        # Initialize OpenAI client
        self.client = OpenAI(api_key=Config.api_key, base_url=Config.base_url)
        self.conversation_history: list[dict[str, Any]] = []

        self.console = Console()
        self.console.print("[red]LLM_Agent start from here.[/red]")

        self.thinking_enabled = getattr(Config, "ENABLE_THINKING", False)
        self.temperature = getattr(Config, "DEFAULT_TEMPERATURE", 0)
        self.total_tokens_used = 0
        self.current_step_index = 0

        # Track current working directory for terminal commands
        self.current_working_directory = str(Config.WORKSPACE_DIR)

        # Context tracking for agentic behavior
        self.context_manager = ContextManager()
        self.auto_tool_selection = False
        self.max_auto_tool_calls = getattr(Config, "MAX_AUTO_TOOL_CALLS", 5)
        self.current_auto_tool_calls = 0

        # Direct MCP connection attributes
        self.mcp_server_url = mcp_server_url
        self.mcp_session: Optional[ClientSession] = None
        self.mcp_exit_stack = AsyncExitStack()
        self.available_mcp_tools: List[Dict[str, Any]] = []
        self._mcp_connected = False

        # Enhanced system prompt with agentic capabilities
        self.system_prompt = f"{SystemPrompts.REVISED_PROMPT}"

        # Call super().__init__ after setting up our attributes
        super().__init__(
            name="LLM_Agent",
            system_message="",
            llm_config={
                "config_list": [
                    {
                        "model": Config.Model,
                        "api_key": Config.api_key,
                        "base_url": Config.base_url,
                    }
                ],
                "timeout": 120,
            },
            description="""
            You are an expert LLM agent equipped with a wide range of tools to help you complete the user's request. It can be the user's query or the steps generated by the Step_Generator agent.
            """,
        )
        self.register_reply(
            trigger=self._always_true_trigger,
            reply_func=self.main,
            position=0,
        )

        # Attempt to connect to MCP server during initialization
        # We need to do this in a non-async way since __init__ is not async
        try:
            import asyncio

            loop = asyncio.get_event_loop()
            if loop.is_running():
                # Create a task to connect later
                asyncio.create_task(self.connect_to_mcp_server())
                self.console.print(
                    "[yellow]Connection to MCP server scheduled as background task[/yellow]"
                )
            else:
                # If loop is not running, we can run it directly
                loop.run_until_complete(self.connect_to_mcp_server())
        except Exception as e:
            self.console.print(
                f"[yellow]Failed to connect to MCP server during initialization: {e}[/yellow]"
            )
            logger.warning(
                f"Failed to connect to MCP server during initialization: {e}"
            )

    def _always_true_trigger(self, sender):
        return True

    async def connect_to_mcp_server(self) -> bool:
        """
        Connect directly to the MCP server via SSE and initialize the session.

        Returns:
            bool: True if connected successfully or already connected, False otherwise
        """
        if self._mcp_connected and self.mcp_session:
            logger.info("Already connected to MCP server.")
            return True

        try:
            logger.info(
                f"Connecting directly to MCP server at {self.mcp_server_url}..."
            )
            self.console.print(
                f"[cyan]Connecting directly to MCP server at {self.mcp_server_url}...[/cyan]"
            )

            # Clean up previous stack if reconnecting
            if self.mcp_exit_stack:
                await self.mcp_exit_stack.aclose()
                self.mcp_exit_stack = AsyncExitStack()

            # Establish SSE connection and ClientSession
            streams = await self.mcp_exit_stack.enter_async_context(
                sse_client(self.mcp_server_url)
            )
            self.mcp_session = await self.mcp_exit_stack.enter_async_context(
                ClientSession(streams[0], streams[1])
            )
            await self.mcp_session.initialize()
            logger.info("MCP Session initialized successfully.")

            # Fetch available tools
            await self._fetch_and_process_mcp_tools()

            self._mcp_connected = True
            self.console.print(
                f"[green]Connected directly to MCP server. Found {len(self.available_mcp_tools)} tools.[/green]"
            )
            logger.info(
                f"Connected to MCP. Available tools: {', '.join(self.get_available_tool_names())}"
            )

            return True
        except Exception as e:
            error_msg = f"Failed to connect directly to MCP server: {str(e)}"
            self.console.print(
                f"[bold red]{error_msg}\n{traceback.format_exc()}[/bold red]"
            )
            logger.error(f"{error_msg}\n{traceback.format_exc()}")
            self._mcp_connected = False
            self.mcp_session = None  # Ensure session is None on failure
            await self.mcp_exit_stack.aclose()  # Clean up stack on failure
            self.mcp_exit_stack = AsyncExitStack()  # Re-initialize stack
            return False

    async def _fetch_and_process_mcp_tools(self):
        """Fetches and processes the list of available tools directly from the MCP session."""
        if not self.mcp_session:
            logger.error("Cannot fetch tools, MCP session not available.")
            self.available_mcp_tools = []
            return

        try:
            logger.info("Fetching available tools directly from MCP session...")
            # Assuming list_tools() returns a result object with a 'tools' attribute or similar
            # Adjust the extraction logic based on the actual return type of
            # self.mcp_session.list_tools()
            tools_result = await self.mcp_session.list_tools()

            # Helper to extract tools from potentially varied result structures
            mcp_tools_raw = self._extract_mcp_data(tools_result, "tools")

            if not isinstance(mcp_tools_raw, list):
                logger.warning(
                    f"Received non-list tools data from MCP: {type(mcp_tools_raw)}"
                )
                mcp_tools_raw = []

            logger.info(f"Found {len(mcp_tools_raw)} raw tools from MCP.")

            # Process each tool into a standardized dictionary format
            processed_tools = []
            for tool_raw in mcp_tools_raw:
                try:
                    processed_tools.append(self._process_mcp_tool_definition(tool_raw))
                except Exception as e:
                    logger.error(
                        f"Error processing raw tool definition: {tool_raw} - Error: {e}"
                    )

            self.available_mcp_tools = processed_tools
            logger.info(f"Processed {len(self.available_mcp_tools)} tools.")

        except Exception as e:
            logger.error(
                f"Failed to fetch or process tools from MCP: {e}\n{traceback.format_exc()}"
            )
            self.available_mcp_tools = []

    def _extract_mcp_data(self, result_obj: Any, expected_attr: str) -> Any:
        """Extracts data from various MCP result object formats."""
        if hasattr(result_obj, expected_attr):
            return getattr(result_obj, expected_attr)
        # Add more checks here if MCP returns results in other formats (e.g.,
        # dict)
        if isinstance(result_obj, dict) and expected_attr in result_obj:
            return result_obj[expected_attr]
        if isinstance(result_obj, list):
            # If the result itself is a list, maybe that's what we want?
            # This depends heavily on the MCP API contract. Assuming list_tools
            # returns an obj with .tools for now.
            logger.warning(
                f"MCP result was a list, expected object with attribute '{expected_attr}'. Returning list."
            )
            return result_obj
        logger.warning(
            f"Could not extract '{expected_attr}' from MCP result type: {type(result_obj)}"
        )
        return None  # Indicate data wasn't found as expected

    def _process_mcp_tool_definition(self, tool_data: Any) -> Dict[str, Any]:
        """Converts a raw tool definition from MCP into a standardized dictionary."""
        processed = {
            "name": "UnknownTool",
            "description": "No description available.",
            "inputSchema": {},
            "annotations": {},
        }

        if isinstance(tool_data, dict):
            processed["name"] = tool_data.get("name", processed["name"])
            processed["description"] = tool_data.get(
                "description", processed["description"]
            )
            processed["inputSchema"] = tool_data.get(
                "inputSchema", tool_data.get("schema", processed["inputSchema"])
            )
            processed["annotations"] = tool_data.get(
                "annotations", processed["annotations"]
            )
        elif hasattr(tool_data, "name"):  # Check for object attributes
            processed["name"] = getattr(tool_data, "name", processed["name"])
            processed["description"] = getattr(
                tool_data, "description", processed["description"]
            )
            # Handle schema attribute possibilities
            if hasattr(tool_data, "inputSchema"):
                processed["inputSchema"] = getattr(
                    tool_data, "inputSchema", processed["inputSchema"]
                )
            elif hasattr(tool_data, "schema"):
                processed["inputSchema"] = getattr(
                    tool_data, "schema", processed["inputSchema"]
                )
            processed["annotations"] = getattr(
                tool_data, "annotations", processed["annotations"]
            )
        else:
            logger.warning(f"Unrecognized raw tool data format: {type(tool_data)}")

        # Ensure inputSchema is a dict
        if not isinstance(processed["inputSchema"], dict):
            logger.warning(
                f"Tool '{processed['name']}' has non-dict inputSchema: {type(processed['inputSchema'])}. Resetting to empty dict."
            )
            processed["inputSchema"] = {}

        return processed

    @property
    def tools(self) -> List[Dict[str, Any]]:
        """
        Get the list of available tools fetched directly from the MCP server.

        Returns:
            List[Dict[str, Any]]: A list of standardized tool definitions
        """
        if not self._mcp_connected or not self.available_mcp_tools:
            self.console.print(
                "[yellow]Warning: Tools property accessed, but not connected to MCP or no tools found.[/yellow]"
            )
            logger.warning(
                "Attempted to access tools property without connection or available tools."
            )
            # Optionally, could attempt a connection here, but safer to rely on explicit connection flow.
            # await self.connect_to_mcp_server() # Avoid await in property
            return []

        return self.available_mcp_tools

    async def refresh_tools(self) -> bool:
        """
        Refresh the list of available tools by reconnecting to the MCP server and fetching tools.

        Returns:
            bool: True if refresh was successful, False otherwise
        """
        self.console.print("[cyan]Refreshing tools directly from MCP server...[/cyan]")
        # Force a reconnect and tool fetch
        self._mcp_connected = False
        self.available_mcp_tools = []
        # Close existing session if any before reconnecting
        if self.mcp_session:
            try:
                await self.mcp_exit_stack.aclose()
                self.mcp_session = None
                self.mcp_exit_stack = (
                    AsyncExitStack()
                )  # Re-initialize for next connection
            except Exception as e:
                logger.error(f"Error closing existing MCP session during refresh: {e}")

        success = await self.connect_to_mcp_server()
        if success:
            self.console.print(
                f"[green]Successfully refreshed tools from MCP. Found {len(self.available_mcp_tools)} tools.[/green]"
            )
        else:
            self.console.print("[red]Failed to refresh tools from MCP server.[/red]")
        return success

    def display_available_tools(self):
        """
        Display all available tools fetched directly from the MCP server.
        """
        self.console.print(
            "\n[bold cyan]Available Tools (Direct MCP Connection):[/bold cyan]"
        )

        if not self._mcp_connected or not self.available_mcp_tools:
            self.console.print(
                "[yellow]No tools available. Ensure connection to MCP server and run 'refresh'.[/yellow]"
            )
            return

        # Sort tools by name for consistent display
        sorted_tools = sorted(self.available_mcp_tools, key=lambda x: x.get("name", ""))

        for idx, tool in enumerate(sorted_tools, 1):
            name = tool.get("name", "Unnamed Tool")
            description = tool.get("description", "No description available")

            # Truncate long descriptions for display
            if len(description) > 100:
                description = description[:97] + "..."

            self.console.print(f"[green]{idx}. [bold]{name}[/bold][/green]")
            self.console.print(f"   {description}")

        self.console.print(f"\n[cyan]Total: {len(sorted_tools)} tools available[/cyan]")

    def get_available_tool_names(self) -> List[str]:
        """Returns a list of available tool names fetched from MCP."""
        return [tool.get("name", "UnknownTool") for tool in self.available_mcp_tools]

    def get_tool_info(self, tool_name: str) -> Optional[Dict[str, Any]]:
        """Returns information about a specific tool fetched from MCP."""
        for tool in self.available_mcp_tools:
            if tool.get("name") == tool_name:
                return tool
        return None

    async def _execute_tool(self, tool_use):
        """
        Execute a tool via the direct MCP session.

        Args:
            tool_use: An object with 'name' and 'input' attributes

        Returns:
            Any: The result of the tool execution, formatted for display.
        """
        tool_name = tool_use.name
        tool_input = tool_use.input

        # Display execution details
        tool_header = Panel(
            f"[bold cyan]Tool:[/bold cyan] {tool_name}\n[bold cyan]Parameters:[/bold cyan]\n{json.dumps(self._clean_data_for_display(tool_input), indent=2)}",
            title="[bold]Tool Execution Details[/bold]",
            border_style="cyan",
            padding=(1, 2),
        )
        self.console.print(tool_header)

        # Store original working directory for potential rollback
        original_working_directory = self.current_working_directory
        command = None  # Initialize command variable

        # Special handling for terminal commands before execution
        if tool_name.lower() == "terminalcommandtool":
            # Ensures working_directory etc. are set
            self._prepare_terminal_command(tool_input)
            command = tool_input.get("command", "")
            # Update agent's working directory *before* execution if it's a
            # 'cd' command
            if command and command.strip().startswith("cd "):
                target_dir = command.strip()[3:].strip()
                current_base_dir_for_cd = tool_input.get(
                    "working_directory", self.current_working_directory
                )
                if not os.path.isabs(target_dir):
                    new_dir = os.path.normpath(
                        os.path.join(current_base_dir_for_cd, target_dir)
                    )
                else:
                    new_dir = target_dir
                if os.path.isdir(new_dir):
                    self.current_working_directory = new_dir
                    self.console.print(
                        f"[green]Agent's working directory updated to: {new_dir} (due to 'cd' command)[/green]"
                    )
                    self.context_manager.current_directories.add(new_dir)

        # Ensure connection and session exist
        if not self._mcp_connected or not self.mcp_session:
            self.console.print(
                "[red]MCP session not available. Attempting to connect...[/red]"
            )
            success = await self.connect_to_mcp_server()
            if not success:
                return f"Error: Failed to connect to MCP server to execute tool '{tool_name}'"

        # Execute the tool via the session
        result = None
        raw_mcp_result = None
        try:
            self.console.print(
                f"[cyan]Executing tool '{tool_name}' via direct MCP session...[/cyan]"
            )
            # No Live spinner here — its refresh thread stalls under eventlet monkey-patching
            raw_mcp_result = await self.mcp_session.call_tool(
                name=tool_name, arguments=tool_input
            )
            self.console.print("[green]MCP Tool execution completed[/green]")

            # Process and format the result
            content_blocks = self._extract_mcp_data(raw_mcp_result, "content")
            if content_blocks is None:
                # Fallback if 'content' attribute doesn't exist, maybe the result itself is the content?
                # This depends on the MCP API contract for call_tool.
                logger.warning(
                    f"Could not find 'content' in MCP result for tool '{tool_name}'. Trying result directly."
                )
                content_blocks = raw_mcp_result  # Use the raw result
                # If raw_mcp_result isn't iterable/list-like, wrap it
                if not isinstance(content_blocks, (list, tuple)):
                    content_blocks = [content_blocks]

            formatted_results = self._format_content_blocks(content_blocks)
            result = (
                "\n".join(formatted_results)
                if formatted_results
                else f"Tool '{tool_name}' executed successfully but returned no displayable content."
            )

            # Post-execution checks (e.g., directory creation)
            if tool_name.lower() == "terminalcommandtool" and command:
                effective_wd = tool_input.get(
                    "working_directory", original_working_directory
                )
                if (
                    "npx create-react-app" in command
                    or "mkdir" in command
                    or "npm init" in command
                    or "yarn create" in command
                ):
                    self._check_for_created_directories(command, result, effective_wd)

        except Exception as exec_err:
            error_message = (
                f"Error executing tool '{tool_name}' via MCP session: {str(exec_err)}"
            )
            self.console.print(
                f"[bold red]{error_message}\n{traceback.format_exc()}[/bold red]"
            )
            logger.error(f"{error_message}\n{traceback.format_exc()}")

            # Rollback working directory on cd error
            if (
                tool_name.lower() == "terminalcommandtool"
                and command
                and command.strip().startswith("cd ")
            ):
                self.current_working_directory = original_working_directory
                self.console.print(
                    f"[yellow]Reverted working directory to: {original_working_directory} due to error.[/yellow]"
                )

            result = error_message  # Return the error message as the result

        # Display formatted tool usage summary
        if getattr(Config, "SHOW_TOOL_USAGE", True):
            # Ensure result is a string for display
            display_result = (
                str(result)
                if result is not None
                else "Execution finished, but no result captured."
            )
            self._display_tool_usage(tool_name, tool_input, display_result)

        # Return the primary formatted result (usually text)
        return result

    def _format_content_blocks(self, blocks: Any) -> List[str]:
        """Formats content blocks from MCP result into displayable strings."""
        formatted = []
        if blocks is None:
            return formatted

        # If blocks is not a list, wrap it
        if not isinstance(blocks, list):
            blocks = [blocks]

        for block in blocks:
            if block is None:
                continue

            block_type = None
            text_content = None
            mime_type = "unknown"

            # Handle dictionary format
            if isinstance(block, dict):
                block_type = block.get("type")
                text_content = block.get("text")
                mime_type = block.get("mimeType", mime_type)
            # Handle object attribute format
            elif hasattr(block, "type"):
                block_type = getattr(block, "type", None)
                if hasattr(block, "text"):
                    text_content = getattr(block, "text", None)
                mime_type = getattr(block, "mimeType", mime_type)
                # Add check for other potential content attributes if needed

            # Format based on type
            if block_type == "text" and text_content is not None:
                formatted.append(str(text_content))
            elif block_type == "image":
                formatted.append(f"[Image data received, mime-type: {mime_type}]")
            # Add handling for other block types (e.g., 'tool_result', 'error')
            # if defined by MCP
            elif block_type == "error" and hasattr(block, "message"):
                formatted.append(f"[MCP Tool Error]: {getattr(block, 'message')}")
            elif text_content is not None:  # Fallback for blocks with text but no type?
                formatted.append(str(text_content))
            else:
                # Fallback for unknown block structure
                try:
                    formatted.append(str(block))
                    logger.debug(f"Formatted unknown MCP block as string: {str(block)}")
                except Exception as format_err:
                    logger.error(f"Could not format unknown MCP block: {format_err}")
                    formatted.append("[Unformattable content block received from MCP]")

        return formatted

    def _display_tool_usage(self, tool_name: str, input_data: dict, result: str):
        """
        Display a tool execution's input and result in a formatted panel.

        Args:
            tool_name: The name of the tool
            input_data: The input parameters for the tool
            result: The result of the tool execution
        """
        if not getattr(Config, "SHOW_TOOL_USAGE", False):
            return

        # Clean up input data by removing any large binary/base64 content
        cleaned_input = self._clean_data_for_display(input_data)

        # Clean up result data
        cleaned_result = self._clean_data_for_display(result)

        # Determine if the result was successful based on improved heuristics
        success = True

        # Try to parse the result as JSON if it's a string
        parsed_result = None
        if isinstance(result, str):
            try:
                parsed_result = json.loads(result)
            except json.JSONDecodeError:
                parsed_result = None
        else:
            parsed_result = result

        # Check for explicit failure indicators
        if parsed_result and isinstance(parsed_result, dict):
            # For dictionary results, check specific failure indicators
            if parsed_result.get("error") or parsed_result.get("failed") is True:
                success = False
            # For file operations, check if there were any failed files
            elif "failed_files" in parsed_result and parsed_result["failed_files"] > 0:
                success = False
            # For results with a success field, use that directly
            elif "success" in parsed_result and parsed_result["success"] is False:
                success = False
        elif isinstance(result, str):
            # For string results, check for positive indicators first
            if "successfully" in result.lower() or "success" in result.lower():
                success = True
            # Then check for error keywords but avoid false positives
            elif (
                "error:" in result.lower()
                or "exception:" in result.lower()
                or result.lower().startswith("error")
                or "not found" in result.lower()
            ):
                success = False

        # Create a more visually appealing result display
        status_icon = "✅" if success else "❌"
        status_color = "green" if success else "red"

        # Format the result for better readability
        if isinstance(cleaned_result, str) and len(cleaned_result) > 500:
            # For long text results, show a preview
            preview = cleaned_result[:500] + "... (truncated)"
            result_display = (
                f"[{status_color}]{status_icon} Result:[/{status_color}]\n{preview}"
            )
        else:
            # For shorter results, show everything
            result_display = f"[{status_color}]{status_icon} Result:[/{status_color}]\n{cleaned_result}"

        # Create a more detailed panel with input and result
        tool_info = f"""[bold cyan]📥 Input Parameters:[/bold cyan]
{json.dumps(cleaned_input, indent=2)}

{result_display}"""

        panel = Panel(
            tool_info,
            title=f"[bold]{tool_name} - Execution Summary[/bold]",
            title_align="center",
            border_style=status_color,
            padding=(1, 2),
        )
        self.console.print(panel)

    def _check_for_created_directories(self, command, result, working_directory):
        """

        After a tool executes (especially terminal commands like cd or mkdir), this function:

            Checks the output to see if a new directory was created.
            Updates the agent's context (e.g., the current working directory and a set of tracked directories) accordingly.
        ------------------
        Check if a command created a new directory and update the working directory if needed.

        Args:
            command: The command that was executed
            result: The result of the command execution
            working_directory: The working directory where the command was executed
        """
        import json
        import re

        # Parse the result if it's a JSON string
        result_data = {}
        if isinstance(result, str):
            try:
                result_data = json.loads(result)
            except json.JSONDecodeError:
                # Not JSON, use the string directly
                result_data = {"stdout": result}
        elif isinstance(result, dict):
            result_data = result

        stdout = result_data.get("stdout", "")

        # Check for common patterns in command output that indicate directory
        # creation
        created_dir = None
        auto_cd = False  # Flag to indicate if we should automatically change directory

        # Pattern for npx create-react-app
        if "npx create-react-app" in command:
            # Extract the app name from the command
            match = re.search(r"npx create-react-app\s+([^\s]+)", command)
            if match:
                app_name = match.group(1)
                potential_dir = os.path.join(working_directory, app_name)
                if os.path.isdir(potential_dir):
                    created_dir = potential_dir
                    self.console.print(
                        f"[green]Detected React app creation in directory: {created_dir}[/green]"
                    )
                    auto_cd = True  # Auto-change to React app directory

        # Pattern for mkdir
        elif "mkdir" in command:
            # Extract directory name from mkdir command
            match = re.search(r"mkdir\s+(-p\s+)?([^\s]+)", command)
            if match:
                dir_name = match.group(2)
                potential_dir = os.path.join(working_directory, dir_name)
                if os.path.isdir(potential_dir):
                    created_dir = potential_dir
                    self.console.print(
                        f"[green]Detected directory creation: {created_dir}[/green]"
                    )
                    # Don't auto-cd for mkdir, as it's often used for utility
                    # directories

        # Pattern for npm init or yarn create
        elif "npm init" in command or "yarn create" in command:
            # Look for common project creation patterns in output
            if "package.json" in stdout:
                # The current directory is likely the project directory
                created_dir = working_directory
                self.console.print(
                    f"[green]Detected project initialization in: {created_dir}[/green]"
                )

        # If a directory was created, suggest it as the new working directory
        if created_dir:
            # Add the new directory to tracked directories
            self.context_manager.current_directories.add(created_dir)

            # Check for important subdirectories
            if os.path.isdir(created_dir):
                subdirs = [
                    d
                    for d in os.listdir(created_dir)
                    if os.path.isdir(os.path.join(created_dir, d))
                ]
                if subdirs:
                    self.console.print(
                        f"[cyan]Found subdirectories in {created_dir}: { ', '.join(subdirs)}[/cyan]"
                    )
                    # Add important subdirectories to tracked directories
                    for subdir in subdirs:
                        if subdir in [
                            "src",
                            "public",
                            "components",
                            "pages",
                            "api",
                            "lib",
                            "utils",
                        ]:
                            full_path = os.path.join(created_dir, subdir)
                            self.context_manager.current_directories.add(full_path)
                            self.console.print(
                                f"[green]Added important subdirectory {full_path} to tracked directories[/green]"
                            )

            # For certain commands like create-react-app, automatically change
            # directory
            if auto_cd:
                self.console.print(
                    f"[yellow]Automatically changing working directory to: {created_dir}[/yellow]"
                )
                self.current_working_directory = created_dir
                # Add a message to the conversation history about the directory
                # change
                self.conversation_history.append(
                    {
                        "role": "assistant",
                        "content": f"I've automatically changed the working directory to the newly created project folder: `{created_dir}`",
                    }
                )
            else:
                # Just suggest changing directory
                self.console.print(
                    f"[yellow]A new directory was created: {created_dir}[/yellow]"
                )
                self.console.print(
                    f"[yellow]You may want to change to this directory with 'cd {os.path.basename(created_dir)}'[/yellow]"
                )

    def _clean_data_for_display(self, data):
        """
        Helper method to clean data for display by handling various data types
        and removing/replacing large content like base64 strings.
        """
        if isinstance(data, str):
            try:
                # Try to parse as JSON first
                parsed_data = json.loads(data)
                return self._clean_parsed_data(parsed_data)
            except json.JSONDecodeError:
                # If it's a long string, check for base64 patterns
                if len(data) > 1000 and ";base64," in data:
                    return "[base64 data omitted]"
                return data
        elif isinstance(data, dict):
            return self._clean_parsed_data(data)
        else:
            return data

    def _clean_parsed_data(self, data):
        """
        Recursively clean parsed JSON/dict data, handling nested structures
        and replacing large data with placeholders.
        """
        if isinstance(data, dict):
            cleaned = {}
            for key, value in data.items():
                # Handle image data in various formats
                if key in ["data", "image", "source"] and isinstance(value, str):
                    if len(value) > 1000 and (
                        ";base64," in value or value.startswith("data:")
                    ):
                        cleaned[key] = "[base64 data omitted]"
                    else:
                        cleaned[key] = value
                else:
                    cleaned[key] = self._clean_parsed_data(value)
            return cleaned
        elif isinstance(data, list):
            return [self._clean_parsed_data(item) for item in data]
        elif isinstance(data, str) and len(data) > 1000 and ";base64," in data:
            return "[base64 data omitted]"
        return data

    def _display_token_usage(self, usage):
        """
        Display a visual representation of token usage and remaining tokens.
        Uses only the tracked total_tokens_used.
        """
        used_percentage = (
            self.total_tokens_used / Config.MAX_CONVERSATION_TOKENS
        ) * 100
        remaining_tokens = max(
            0, Config.MAX_CONVERSATION_TOKENS - self.total_tokens_used
        )

        self.console.print(
            f"\nTotal used: {self.total_tokens_used:,} / {Config.MAX_CONVERSATION_TOKENS:,}"
        )

        bar_width = 40
        filled = int(used_percentage / 100 * bar_width)
        bar = "█" * filled + "░" * (bar_width - filled)

        color = "green"
        if used_percentage > 75:
            color = "yellow"
        if used_percentage > 90:
            color = "red"

        self.console.print(f"[{color}][{bar}] {used_percentage:.1f}%[/{color}]")

        if remaining_tokens < 20000:
            self.console.print(
                f"[bold red]Warning: Only {remaining_tokens:,} tokens remaining![/bold red]"
            )

        self.console.print("---")

    async def _get_openai_formatted_tools_from_mcp(self):
        """
        Fetch tools directly from MCP and format them for the OpenAI API.
        Includes truncation of long descriptions and proper schema conversion.

        Returns:
            List[Dict]: A list of tool definitions formatted for OpenAI's tool calling API
        """
        # Ensure we're connected to MCP
        success = await self.connect_to_mcp_server()
        if not success:
            self.console.print(
                "[yellow]No MCP connection available for tool fetching.[/yellow]"
            )
            logger.warning("Failed to fetch tools from MCP - no connection")
            return []

        # Use the tools fetched during connection/refresh
        mcp_tools = self.available_mcp_tools
        if not mcp_tools:
            self.console.print(
                "[yellow]No tools available from MCP cache. Did connection/fetch fail?[/yellow]"
            )
            logger.warning("No tools available in self.available_mcp_tools")
            return []

        # Format the tools for OpenAI's tools API
        openai_tools = []
        for mcp_tool in mcp_tools:
            try:
                # Get the tool schema from MCP - inputSchema or schema fields
                parameters = {}
                if "inputSchema" in mcp_tool:
                    parameters = mcp_tool["inputSchema"]
                elif "schema" in mcp_tool:
                    parameters = mcp_tool["schema"]

                # Format the tool for OpenAI
                formatted_tool = {
                    "type": "function",
                    "function": {
                        "name": mcp_tool.get("name", ""),
                        "description": mcp_tool.get("description", ""),
                        "parameters": parameters,
                    },
                }

                # Truncate descriptions if too long (OpenAI API has limits)
                if len(formatted_tool["function"]["description"]) > 1000:
                    formatted_tool["function"]["description"] = (
                        formatted_tool["function"]["description"][:997] + "..."
                    )

                # Truncate parameter descriptions
                if isinstance(parameters, dict):
                    if (
                        "description" in parameters
                        and len(parameters["description"]) > 1000
                    ):
                        parameters["description"] = (
                            parameters["description"][:997] + "..."
                        )

                    # Truncate properties descriptions
                    if "properties" in parameters and isinstance(
                        parameters["properties"], dict
                    ):
                        for property_name, property_def in parameters[
                            "properties"
                        ].items():
                            if (
                                isinstance(property_def, dict)
                                and "description" in property_def
                            ):
                                if len(property_def["description"]) > 1000:
                                    property_def["description"] = (
                                        property_def["description"][:997] + "..."
                                    )

                openai_tools.append(formatted_tool)
            except Exception as e:
                logger.error(
                    f"Error formatting tool {mcp_tool.get('name', 'unknown')}: {str(e)}"
                )
                continue

        logger.info(f"Formatted {len(openai_tools)} tools for OpenAI API")
        return openai_tools

    async def _get_completion(self):
        """
        Get a completion from the OpenAI API with tool calling capabilities.

        This function:
        1. Gets and formats tools from MCP for OpenAI's API
        2. Makes the API call and processes the response
        3. If tool calls are returned, executes each tool and adds results to conversation
        4. Recursively calls itself until no more tool calls are needed

        Returns:
            str: The final response from the assistant
        """
        from openai import OpenAI
        import traceback

        # Recreate the client to ensure fresh connections
        self.client = OpenAI(api_key=Config.api_key, base_url=Config.base_url)

        try:
            # Get tools formatted for OpenAI from MCP
            formatted_tools = await self._get_openai_formatted_tools_from_mcp()
            self.console.print(
                f"[cyan]Sending request with {len(formatted_tools)} tools...[/cyan]"
            )

            # Prepare conversation history
            messages = self.conversation_history.copy()

            # Create the completion (no Live spinner — its thread.join() stalls
            # under eventlet monkey-patching)
            self.console.print("[cyan]Sending LLM request…[/cyan]")
            response = self.client.chat.completions.create(
                model=Config.Model,
                messages=messages,
                max_tokens=min(
                    Config.MAX_TOKENS,
                    Config.MAX_CONVERSATION_TOKENS - self.total_tokens_used,
                ),
                temperature=self.temperature,
                tools=formatted_tools,
            )
            self.console.print("[green]LLM response received.[/green]")

            # If assistant returns a text response (no tool calls), add it to history
            if response.choices[0].message.content:
                self.conversation_history.append(
                    {
                        "role": "assistant",
                        "content": response.choices[0].message.content,
                    }
                )

            # Update token usage stats and push to UI
            if hasattr(response, "usage") and response.usage:
                usage = response.usage
                message_tokens = usage.prompt_tokens + usage.completion_tokens
                self.total_tokens_used += message_tokens
                self._display_token_usage(usage)
                # Emit to workflow panel if context is available
                ctx = getattr(self, "context", None)
                if ctx:
                    emit_tok = ctx.get("emit_token_usage")
                    wid = ctx.get("workflow_id", "")
                    if emit_tok and wid:
                        emit_tok(
                            wid,
                            usage.prompt_tokens,
                            usage.completion_tokens,
                            self.total_tokens_used,
                            Config.MAX_CONVERSATION_TOKENS,
                        )

            if self.total_tokens_used >= Config.MAX_CONVERSATION_TOKENS:
                self.console.print(
                    "\n[bold red]Token limit reached! Please reset the conversation.[/bold red]"
                )
                return "Token limit reached! Please type 'reset' to start a new conversation."

            # Check if the assistant wants to use tools
            if (
                hasattr(response.choices[0].message, "tool_calls")
                and response.choices[0].message.tool_calls
            ):
                # Process and execute the tool calls
                return await self._process_tool_calls(
                    response.choices[0].message.tool_calls
                )
            else:
                # No tool calls, just return the content
                import re

                if response.choices and len(response.choices) > 0:
                    final_content = response.choices[0].message.content or ""
                    final_content = final_content.strip()

                    # Check if this is a final JSON response
                    is_final_response = False
                    try:
                        json.loads(final_content)
                        is_final_response = True
                    except json.JSONDecodeError:
                        # Check for JSON embedded in text
                        pattern = re.compile(r"({.*})", re.DOTALL)
                        match = pattern.search(final_content)
                        if match:
                            candidate_json = match.group(1)
                            try:
                                json.loads(candidate_json)
                                final_content = candidate_json
                                is_final_response = True
                            except json.JSONDecodeError:
                                pass

                    # If not a final response and we're in auto mode, prompt for tool use
                    if not is_final_response and self.auto_tool_selection:
                        self.console.print(
                            "\n[yellow]No tool calls detected and response is not a final JSON report. Requesting completion again...[/yellow]"
                        )
                        self.conversation_history.append(
                            {
                                "role": "user",
                                "content": f"Make sure to always use tools unless you are sure that the query is complete. Original query: \n{self.user_input}\n. If the query is complete, return the final answer without any additional text.",
                            }
                        )
                        return await self._get_completion()

                    # Reset the auto tool call counter (since we have a final answer)
                    self.current_auto_tool_calls = 0

                    # Save the response in context memory if needed
                    if hasattr(self.context_manager, "report_memory"):
                        self.context_manager.report_memory.append(
                            {
                                "role": "system",
                                "content": f"report summary for step {self.current_step_index}: {final_content}",
                            }
                        )

                    return final_content
                else:
                    return "No response generated."

        except Exception as e:
            logger.error(
                f"Error in _get_completion: {str(e)}\n{traceback.format_exc()}"
            )

            if "closing tag" in str(e) and "doesn't match any open tag" in str(e):
                logger.error("XML tag mismatch detected in response")
                import re

                tag_match = re.search(r"closing tag '([^']+)'", str(e))
                problematic_tag = tag_match.group(1) if tag_match else "unknown"
                logger.error(f"Problematic tag: {problematic_tag}")
                return "Error: There's an issue with the formatting of the response. Please check the template tags in your agent definitions."

            error_msg = f"Error: {str(e)}"
            error_msg = error_msg.replace("[", r"\\[").replace("]", r"\\]")
            return error_msg

    async def _process_tool_calls(self, tool_calls):
        """
        Process and execute tool calls from the OpenAI API response.

        Args:
            tool_calls: The tool_calls list from OpenAI's API response

        Returns:
            str: The final response after executing all tools
        """
        self.console.print(
            "\n[bold yellow]Starting workflow execution...[/bold yellow]\n"
        )

        # Increment the auto tool call counter
        self.current_auto_tool_calls += 1
        if self.current_auto_tool_calls > self.max_auto_tool_calls:
            self.console.print(
                "[red]Too many automatic tool call iterations. Aborting further tool executions.[/red]"
            )
            return "Aborted: maximum recursive tool calls reached."

        # Create a workflow plan
        plan_summary = "I'll execute the following workflow:\n\n"
        workflow_steps = []

        for i, tool_call in enumerate(tool_calls):
            tool_name = tool_call.function.name
            try:
                tool_input = json.loads(tool_call.function.arguments)
            except json.JSONDecodeError as e:
                logger.warning(f"Could not parse arguments for tool '{tool_name}': {e}")
                tool_input = {}
            step_num = i + 1
            action_desc = self._get_action_description(tool_name, tool_input)

            plan_summary += f"Step {step_num}: {action_desc}\n"
            workflow_steps.append(
                {
                    "number": step_num,
                    "tool": tool_name,
                    "description": action_desc,
                    "input": tool_input,
                }
            )

        # Display and log workflow steps
        self.console.print("\n[bold green]Workflow Plan:[/bold green]")
        for step in workflow_steps:
            step_panel = Panel(
                f"[cyan]Tool:[/cyan] {step['tool']}\n[cyan]Action:[/cyan] {step['description']}",
                title=f"[bold]Step {step['number']}/{len(workflow_steps)}[/bold]",
                border_style="blue",
                padding=(1, 2),
            )
            self.console.print(step_panel)

        # Add plan to conversation history
        self.conversation_history.append({"role": "assistant", "content": plan_summary})

        # Helper: emit a step to the workflow panel
        def _ws_step(msg: str, status: str = "complete") -> None:
            ctx = getattr(self, "context", None)
            if not ctx:
                return
            emit_fn = ctx.get("emit_workflow_step")
            wid = ctx.get("workflow_id", "")
            if emit_fn and wid:
                emit_fn(wid, "LLM_Agent", msg, status)

        # Helper: push workspace file tree to client after a tool writes files
        _FILE_MUTATING_TOOLS = {
            "filecreatortool", "fileedittool", "createfolderstool",
            "diffeditortool", "terminalcommandtool", "uvpackagemanager",
        }

        def _ws_fs(tool: str) -> None:
            if tool.lower() not in _FILE_MUTATING_TOOLS:
                return
            ctx = getattr(self, "context", None)
            if not ctx:
                return
            emit_fn = ctx.get("emit_file_system")
            wid = ctx.get("workflow_id", "")
            if emit_fn and wid:
                emit_fn(wid)

        # Execute each tool call sequentially
        for i, tool_call in enumerate(tool_calls):
            tool_name = tool_call.function.name
            try:
                tool_input = json.loads(tool_call.function.arguments)
            except json.JSONDecodeError as e:
                logger.warning(f"Skipping tool '{tool_name}' — bad JSON arguments: {e}")
                _ws_step(f"⚠️ Skipped {tool_name} (malformed arguments — response may have been truncated)", "error")
                continue
            step_num = i + 1
            action_desc = self._get_action_description(tool_name, tool_input)

            # Emit "active" step before execution
            _ws_step(f"🔧 [{step_num}/{len(tool_calls)}] {action_desc}", "active")

            # Pretty header for this step
            step_header = f"[bold white on blue] STEP {step_num}/{len(tool_calls)} [/bold white on blue] [bold cyan]{action_desc}[/bold cyan]"
            self.console.print(f"\n{step_header}")

            # Update context based on the tool
            self._update_context_for_tool(tool_name, tool_input)

            # Special handling for terminal commands
            if tool_name.lower() == "terminalcommandtool":
                self._prepare_terminal_command(tool_input)

            # Execute the tool
            class ToolUseMock:
                """Mock object to hold tool call details"""

                def __init__(self, name, input_data):
                    self.name = name
                    self.input = input_data

            tool_use = ToolUseMock(tool_name, tool_input)
            result = await self._execute_tool(tool_use)

            # Push updated workspace tree immediately after any file-writing tool
            _ws_fs(tool_name)

            # Emit "complete" step after execution
            _ws_step(f"✅ [{step_num}/{len(tool_calls)}] {action_desc}", "complete")

            # Add the tool call to conversation history in OpenAI's expected format
            self.conversation_history.append(
                {
                    "role": "assistant",
                    "content": None,
                    "tool_calls": [
                        {
                            "id": tool_call.id,
                            "type": "function",
                            "function": {
                                "name": tool_name,
                                "arguments": json.dumps(tool_input),
                            },
                        }
                    ],
                }
            )

            # Add the tool response to conversation history
            # Ensure the result is stringified and JSON serializable
            result_str = str(result) if result is not None else "No result"
            self.conversation_history.append(
                {
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "name": tool_name,
                    "content": result_str,
                }
            )

            # Handle special case for directory listing
            if tool_name.lower() == "list_directory" and "No files found" in str(
                result
            ):
                self.console.print(
                    f"[yellow]Directory {tool_input.get('directory_path', '')} appears to be empty.[/yellow]"
                )

            self.console.print(f"[bold green]✓ Step {step_num} completed[/bold green]")

        self.console.print(
            "\n[bold green on white] WORKFLOW COMPLETED [/bold green on white] All steps executed successfully.\n"
        )

        # After executing ALL tools, call _get_completion again to get the final response
        return await self._get_completion()

    def _get_action_description(self, tool_name: str, tool_input: dict) -> str:
        """
        Create a human-readable description of a tool action.

        Args:
            tool_name: The name of the tool
            tool_input: The parameters for the tool

        Returns:
            A human-readable description of what the tool will do
        """
        try:
            # File creation
            if tool_name.lower() == "filecreatortool":
                if isinstance(tool_input.get("files"), dict):
                    path = tool_input["files"].get("path", "unknown")
                    content_preview = tool_input["files"].get("content", "")
                    return f"Creating file '{path}' with content starting with '{content_preview}'"
                elif (
                    isinstance(tool_input.get("files"), list)
                    and len(tool_input["files"]) > 0
                ):
                    if len(tool_input["files"]) == 1:
                        path = tool_input["files"][0].get("path", "unknown")
                        content_preview = tool_input["files"][0].get("content", "")
                        return f"Creating file '{path}' with content starting with '{content_preview}'"
                    else:
                        file_names = [
                            f"'{f.get('path', 'unknown')}'" for f in tool_input["files"]
                        ]
                        return f"Creating {len(file_names)} files: { ', '.join(file_names[:3])}{'... ' if len(file_names) > 3 else ''}"
                return "Creating file(s)"

            # Directory creation
            elif tool_name.lower() == "createfolderstool":
                folder_paths = tool_input.get(
                    "folder_paths", tool_input.get("paths", [])
                )
                if isinstance(folder_paths, list) and len(folder_paths) > 0:
                    if len(folder_paths) == 1:
                        return f"Creating directory '{folder_paths[0]}'"
                    else:
                        dir_names = [f"'{path}'" for path in folder_paths]
                        return f"Creating {len(dir_names)} directories: { ', '.join(dir_names[:3])}{'... ' if len(dir_names) > 3 else ''}"
                return "Creating directories"

            # File reading
            elif tool_name.lower() == "filecontentreadertool":
                file_paths = tool_input.get("file_paths", [])
                if isinstance(file_paths, list) and len(file_paths) > 0:
                    if len(file_paths) == 1:
                        return f"Reading content of file '{file_paths[0]}'"
                    else:
                        file_names = [f"'{path}'" for path in file_paths]
                        return f"Reading {len(file_names)} files: { ', '.join(file_names[:3])}{'... ' if len(file_names) > 3 else ''}"
                return "Reading file content(s)"

            # Directory listing
            elif tool_name.lower() == "list_directory":
                directory_path = tool_input.get("directory_path", "")
                return f"Listing contents of directory '{directory_path}'"

            # File editing/updating
            elif tool_name.lower() == "fileupdatertool":
                if "file_path" in tool_input:
                    content_preview = tool_input.get("content", "")
                    if content_preview and len(content_preview) > 30:
                        content_preview = content_preview[:30] + "..."
                        return f"Updating file '{tool_input['file_path']}' with content starting with '{content_preview}'"
                    return f"Updating file '{tool_input['file_path']}'"
                return "Updating file content"

            # Install package
            elif tool_name.lower() == "uvpackagemanager":
                packages = tool_input.get("packages", [])
                command = tool_input.get("command", "install")
                if isinstance(packages, list) and len(packages) > 0:
                    if len(packages) == 1:
                        return f"{command.capitalize()}ing package '{packages[0]}'"
                    else:
                        package_names = [f"'{pkg}'" for pkg in packages]
                        return f"{command.capitalize()}ing {len(package_names)} packages: { ', '.join(package_names[:3])}{'... ' if len(package_names) > 3 else ''}"
                return f"{command.capitalize()}ing packages"

            # Web search
            elif tool_name.lower() == "websearchtool":
                query = tool_input.get("query", "")
                return f"Searching the web for '{query}'"

            # Code search
            elif tool_name.lower() == "codesearchtool":
                query = tool_input.get("query", "")
                return f"Searching codebase for '{query}'"

            # Terminal command
            elif tool_name.lower() == "terminalcommandtool":
                command = tool_input.get("command", "")
                working_dir = tool_input.get("working_directory", "current directory")
                run_in_background = tool_input.get("run_in_background", False)

                if run_in_background:
                    return f"Running command in background: '{command}' in directory '{working_dir}'"
                else:
                    return f"Executing terminal command: '{command}' in directory '{working_dir}'"

            # Default description with more details
            param_preview = ", ".join(
                [f"{k}={str(v)[:20]}" for k, v in tool_input.items()][:3]
            )
            if len(tool_input) > 3:
                param_preview += "..."
            return f"Using {tool_name} with parameters: {param_preview}"

        except Exception as e:
            logging.error(f"Error creating action description: {str(e)}")
            return f"Using {tool_name}"

    def _update_context_for_tool(self, tool_name: str, tool_input: dict):
        """
        Update the agent's context based on the tool being called.
        This helps with tracking files, directories, and other contextual information.

        Args:
            tool_name: The name of the tool
            tool_input: The parameters for the tool
        """
        # Update context for file reading tools
        if tool_name.lower() == "filecontentreadertool" and "file_paths" in tool_input:
            for file_path in tool_input["file_paths"]:
                if os.path.isfile(file_path):
                    self.context_manager.current_files.add(file_path)
                    self.console.print(
                        f"[dim]Adding file to context: {file_path}[/dim]"
                    )
                elif os.path.isdir(file_path):
                    self.context_manager.current_directories.add(file_path)
                    self.console.print(
                        f"[dim]Adding directory to context: {file_path}[/dim]"
                    )

        # Update context for directory listing tools
        elif tool_name.lower() == "list_directory" and "directory_path" in tool_input:
            directory_path = tool_input["directory_path"]
            if os.path.isdir(directory_path):
                self.context_manager.current_directories.add(directory_path)
                self.console.print(
                    f"[dim]Adding directory to context: {directory_path}[/dim]"
                )

        # Update context for file creation tools
        elif tool_name.lower() == "filecreatortool" and "files" in tool_input:
            files = tool_input["files"]
            if isinstance(files, list):
                for file_info in files:
                    if isinstance(file_info, dict) and "path" in file_info:
                        self.context_manager.current_files.add(file_info["path"])
                        self.console.print(
                            f"[dim]Adding new file to context: {file_info['path']}[/dim]"
                        )
            elif isinstance(files, dict) and "path" in files:
                self.context_manager.current_files.add(files["path"])
                self.console.print(
                    f"[dim]Adding new file to context: {files['path']}[/dim]"
                )

    def _prepare_terminal_command(self, tool_input: dict):
        """
        Prepare terminal command tool inputs with necessary context.

        Args:
            tool_input: The parameters for the terminal command tool
        """
        # Check if the command might be interactive
        command = tool_input.get("command", "")
        interactive_commands = [
            "npm",
            "npx",
            "yarn",
            "create-react-app",
            "read",
            "python -m pip",
            "pip install",
            "apt",
            "apt-get",
        ]

        # Set interactive flag if needed and not already set
        is_interactive = any(cmd in command for cmd in interactive_commands)
        if is_interactive and "interactive" not in tool_input:
            tool_input["interactive"] = True
            self.console.print(
                "[yellow]Command appears to be interactive. Setting interactive mode.[/yellow]"
            )

        # Ensure project_root is set
        if "project_root" not in tool_input:
            project_root = str(Config.WORKSPACE_DIR)
            tool_input["project_root"] = project_root
            self.console.print(
                f"[yellow]Setting project_root to current directory: {project_root}[/yellow]"
            )

        # Ensure working_directory is set
        if "working_directory" not in tool_input:
            tool_input["working_directory"] = self.current_working_directory
            self.console.print(
                f"[yellow]Setting working_directory to tracked directory: {self.current_working_directory}[/yellow]"
            )

    async def reset(self):
        """
        Reset the conversation history, token count, and other stateful information.
        Note that MCP connection is maintained.
        """
        self.console.print("\n[bold yellow]Resetting conversation...[/bold yellow]")

        # Clear conversation history
        self.conversation_history = []

        # Reset token count
        self.total_tokens_used = 0

        # Reset working directory
        self.current_working_directory = str(Config.WORKSPACE_DIR)

        # Reset context manager
        self.context_manager = ContextManager()
        self.current_auto_tool_calls = 0

        # Re-add the system prompt
        self.conversation_history.append(
            {"role": "system", "content": self.system_prompt}
        )

        # Add any existing report memory
        if (
            hasattr(self.context_manager, "report_memory")
            and self.context_manager.report_memory
        ):
            self.conversation_history.extend(self.context_manager.report_memory)

        self.console.print("[bold green]Conversation reset successfully![/bold green]")

        # Display welcome message
        welcome_text = """
# Claude Engineer v3 with MCP Integration

Type 'refresh' to reload available tools from MCP
Type 'reset' to clear conversation history
Type 'info' to display conversation information
Type 'quit' to exit
"""
        self.console.print(Markdown(welcome_text))
        self.console.print(
            "[cyan]Use 'display_available_tools' to see available MCP tools[/cyan]"
        )

        return True

    async def cleanup(self):
        """
        Clean up resources, close the direct MCP connection, and prepare for shutdown.

        This should be called when the agent is no longer needed.
        """
        self.console.print(
            "[yellow]Cleaning up LLM_Agent resources and MCP connection...[/yellow]"
        )

        # Clean up MCP session and connection stack
        if self.mcp_session:
            self.console.print("[cyan]Closing direct MCP session...[/cyan]")
            try:
                await self.mcp_exit_stack.aclose()
                self.console.print(
                    "[green]MCP session and connection stack closed successfully.[/green]"
                )
            except Exception as e:
                self.console.print(f"[red]Error closing MCP session/stack: {str(e)}")
                logger.error(
                    f"Error cleaning up MCP exit stack: {e}\n{traceback.format_exc()}"
                )
        else:
            # Ensure stack is closed even if session wasn't established but stack was created
            try:
                await self.mcp_exit_stack.aclose()
            except Exception as e:
                logger.debug(
                    f"Minor error closing potentially empty MCP exit stack: {e}"
                )

        # Reset state variables
        self.mcp_session = None
        self._mcp_connected = False
        self.available_mcp_tools = []
        self.mcp_exit_stack = AsyncExitStack()  # Re-initialize for potential reuse?

        self.console.print("[green]LLM_Agent cleanup completed[/green]")

    async def chat(self, user_input):
        """
        Process a message from the user and generate a response.

        This method:
        1. Handles special commands (refresh, reset, info, quit)
        2. Adds the user message to conversation history
        3. Gets a completion from the model
        4. Ensures directories and files are properly explored

        Args:
            user_input: The user's message (string or multimodal content)

        Returns:
            str: The response to the user
        """
        # Handle special commands
        if isinstance(user_input, str):
            if user_input.lower() == "refresh":
                success = await self.refresh_tools()
                if success:
                    self.display_available_tools()
                    return "Tools refreshed successfully from MCP server."
                else:
                    return "Failed to refresh tools. Check MCP server connection."

            elif user_input.lower() == "reset":
                await self.reset()
                return "Conversation reset! Ready for new requests."

            elif user_input.lower() == "quit":
                return "Goodbye! Session ended."

            elif user_input.lower() == "info":
                return self._display_conversation_info()

            elif (
                user_input.lower() == "tools"
                or user_input.lower() == "display_available_tools"
            ):
                self.display_available_tools()
                return f"Displayed {len(self.tools)} available tools from MCP server."

        try:
            # Connect to MCP if not already connected
            await self.connect_to_mcp_server()

            # Add the user message to conversation history
            self.conversation_history.append({"role": "user", "content": user_input})

            # Reset the tool call counter for this new interaction
            self.current_auto_tool_calls = 0

            # Display thinking indicator if enabled
            if self.thinking_enabled:
                self.console.print("[cyan]Thinking...[/cyan]")

            # Store the user input for reference in recursive completions
            self.user_input = user_input

            # Get the completion
            response = await self._get_completion()

            # After getting a response, verify context and directories
            await self._ensure_directories_explored()
            await self._check_mentioned_files()

            return response

        except Exception as e:
            import traceback

            error_msg = f"Error in chat: {str(e)}"
            logger.error(f"{error_msg}\n{traceback.format_exc()}")

            if "closing tag" in str(e) and "doesn't match any open tag" in str(e):
                return "Error: There's an issue with the formatting of the response. Please check the template tags."

            error_msg = error_msg.replace("[", r"\\[").replace("]", r"\\]")
            return error_msg

    async def main(self, *args, **kwargs):
        """
        Main entry point for the agent when used with AutoGen.

        Args:
            *args: Variable length argument list
            **kwargs: Arbitrary keyword arguments

        Returns:
            tuple: (final, reply) where final is a boolean indicating if the conversation should end,
                  and reply is the response message
        """
        try:
            # Ensure connection to MCP server
            success = await self.connect_to_mcp_server()
            if not success:
                return True, {
                    "role": "assistant",
                    "content": "Failed to connect to MCP server. Please check connection and try again.",
                }

            # Reset conversation state
            await self.reset()

            final_response_content = "No specific outcome determined."

            # Process messages from AutoGen
            if args or kwargs:
                messages = kwargs.get("messages", [])
                if messages:
                    last_message = messages[-1]
                    sender_name = last_message.get("name", "")
                    content = last_message.get("content", "")

                    if sender_name == "UserProxyAgent":
                        self.console.print(
                            f"[cyan]Received request from UserProxyAgent: {content}[/cyan]"
                        )
                        response = await self.chat(content)
                        # The 'response' from chat is the direct result of that interaction.
                        # The overall summary will be generated after this block.
                        final_response_content = response

                    self.console.print(
                        f"[cyan]Processing message from {sender_name}: {content}[/cyan]"
                    )

                    # Handle step-based execution
                    if hasattr(self, "context") and "steps" in self.context:
                        step_keys = sorted(
                            [
                                k
                                for k in self.context["steps"].keys()
                                if k.startswith("step")
                            ]
                        )

                        step_response = "No specific step response."
                        while self.current_step_index < len(step_keys):
                            current_step_key = step_keys[self.current_step_index]
                            current_step = self.context["steps"][current_step_key]

                            if (
                                isinstance(current_step, dict)
                                and "description" in current_step
                            ):
                                step_description = current_step["description"]
                                step_details = current_step.get("details", "")

                                self.console.print(
                                    f"[bold cyan]Processing step {self.current_step_index + 1}/{len(step_keys)}: {step_description}[/bold cyan]"
                                )
                                self.current_step_index += 1

                                step_response = await self.chat(
                                    f"Execute step: {step_description}\n\nDetails: {step_details}"
                                )
                            else:
                                self.console.print(
                                    f"[bold cyan]Processing step {self.current_step_index + 1}/{len(step_keys)}[/bold cyan]"
                                )
                                self.current_step_index += 1

                                step_response = await self.chat(
                                    f"Execute step: {current_step}"
                                )

                        self.console.print(
                            "[bold yellow]All steps completed.[/bold yellow]"
                        )
                        final_response_content = (
                            step_response  # The result of the last step
                        )
                        # The summary will be generated after this block.

                    # If not UserProxyAgent and not step-based, it might be another agent.
                    # For now, the last response from chat will be the basis if no other logic
                    # overrides.
                    elif not sender_name == "UserProxyAgent":
                        final_response_content = await self.chat(content)

            # Try to extract user input from various sources if not already handled by
            # UserProxyAgent or steps
            if (
                final_response_content == "No specific outcome determined."
            ):  # Indicates UserProxyAgent/steps didn't set it
                user_input = ""
                # From context
                if hasattr(self, "context"):
                    user_input = self.context.get("user_input", "")

                # From messages
                if not user_input and (args or kwargs):
                    messages = kwargs.get("messages", [])
                    if messages:
                        user_input = messages[-1].get("content", "")

                # If no user input found, this path might not be hit if UserProxyAgent or steps always provide input.
                # If it IS hit, it means the agent was invoked by AutoGen without a clear
                # initial task in the typical flow.
                if not user_input:
                    self.console.print(
                        "[yellow]LLM_Agent.main was called without a clear user_input from known sources. Returning pending state.[/yellow]"
                    )
                    return False, {
                        "role": "assistant",
                        "content": "LLM Agent with MCP initialized and awaiting further input or termination.",
                    }

                # Handle special commands if user_input was found this way
            if user_input.lower() == "quit":
                self.console.print(
                    "\n[bold blue]👋 Goodbye! (quit command via main loop)[/bold blue]"
                )
                final_response_content = "Execution quit by command."
                # Summary will still be generated for actions before quit
            elif user_input.lower() == "reset":
                await self.reset()
                # This effectively restarts the main logic for the current AutoGen message
                return await self.main(*args, **kwargs)
            else:
                # Process this directly found user_input
                self.console.print(
                    f"[cyan]Processing direct user_input in main: {user_input}[/cyan]"
                )
                final_response_content = await self.chat(user_input)

            # Generate and return the final summary of all actions performed in this main() call
            final_summary = self._generate_final_summary()

            # Log the original intended response before overriding with summary, if it
            # was substantial
            if (
                final_response_content
                not in ["No specific outcome determined.", "Execution quit by command."]
                and final_response_content != final_summary
            ):
                logger.info(
                    f"Original final response content (before summary): {final_response_content}"
                )

            self.console.print(
                f"\n[bold magenta]Final Summary for Central Manager:[/bold magenta]\n{final_summary}"
            )
            return True, {"role": "assistant", "content": final_summary}

        except KeyboardInterrupt:
            self.console.print(
                "\n[bold yellow]Operation interrupted by user[/bold yellow]"
            )
            return True, {
                "role": "assistant",
                "content": "Operation interrupted by user",
            }

        except Exception as e:
            import traceback

            error_msg = f"Critical error in main: {str(e)}"
            self.console.print(f"[bold red]{error_msg}[/bold red]")
            logger.error(f"{error_msg}\n{traceback.format_exc()}")
            return True, {"role": "assistant", "content": f"Critical error: {str(e)}"}

    def _generate_final_summary(self) -> str:
        """
        Generate a summary of all steps performed during the current agent execution.
        This summary is compiled from the agent's report_memory.

        Returns:
            str: A formatted string summarizing the steps performed.
        """
        if not self.context_manager.report_memory:
            logger.info("No steps recorded in report_memory to summarize.")
            return "No specific actions were recorded to summarize for this task."

        summary_parts = ["Summary of actions performed:"]
        for idx, entry in enumerate(self.context_manager.report_memory):
            content = entry.get("content", "")

            # Try to extract a cleaner step summary from the typical format
            # "report summary for step X: {actual_report_content}"
            match = re.search(
                r"report summary for step\s*\d+:\s*(.*)",
                content,
                re.DOTALL | re.IGNORECASE,
            )
            if match:
                step_report = match.group(1).strip()
                # Prepend with a step number if not already clear from the report itself
                # However, the report_memory entries might not correspond 1:1 with original step numbers if there were retries or sub-steps.
                # Using enumerate index for clarity here.
                summary_parts.append(f"Action {idx + 1}: {step_report}")
            else:
                # Fallback if the content doesn't match the expected prefix
                summary_parts.append(f"Action {idx + 1}: {content}")

        final_summary = "\n".join(summary_parts)
        logger.info(f"Generated final summary: {final_summary}")
        return final_summary

    async def _ensure_directories_explored(self):
        """
        Ensure that all directories in the current context are explored for file content.
        This method checks if directories have been properly explored and contain files.
        If a directory appears to be empty or unexplored, it will trigger a list_directory
        tool call to explore it.
        """
        if not hasattr(self, "context_manager") or not hasattr(
            self.context_manager, "current_directories"
        ):
            return

        for directory in list(self.context_manager.current_directories):
            if not os.path.exists(directory):
                self.console.print(
                    f"[yellow]Directory {directory} does not exist. Removing from context.[/yellow]"
                )
                self.context_manager.current_directories.remove(directory)
                continue

            try:
                # Check if directory is empty
                contents = os.listdir(directory)
                if not contents:
                    self.console.print(
                        f"[yellow]Directory {directory} is empty.[/yellow]"
                    )
                    continue

                # Check if we have explored this directory (if any files from this
                # directory are in current_files)
                directory_explored = False
                for file in self.context_manager.current_files:
                    if file.startswith(directory):
                        directory_explored = True
                        break

                if not directory_explored:
                    self.console.print(
                        f"[yellow]Directory {directory} has not been explored. Exploring...[/yellow]"
                    )

                    # Create a mock tool use object for list_directory
                    class ToolUseMock:
                        def __init__(self, name, input_data):
                            self.name = name
                            self.input = input_data

                    tool_use = ToolUseMock(
                        "list_directory", {"directory_path": directory}
                    )
                    result = await self._execute_tool(tool_use)

                    # Add the tool call and result to conversation history
                    tool_call_id = f"auto_list_{directory}"
                    self.conversation_history.append(
                        {
                            "role": "assistant",
                            "content": None,
                            "tool_calls": [
                                {
                                    "id": tool_call_id,
                                    "type": "function",
                                    "function": {
                                        "name": "list_directory",
                                        "arguments": json.dumps(
                                            {"directory_path": directory}
                                        ),
                                    },
                                }
                            ],
                        }
                    )

                    self.conversation_history.append(
                        {
                            "role": "tool",
                            "tool_call_id": tool_call_id,
                            "name": "list_directory",
                            "content": str(
                                result
                            ),  # Ensure result is JSON serializable string
                        }
                    )

                    self.console.print(
                        f"[green]Directory {directory} explored.[/green]"
                    )

                    # Check if the directory needs deeper exploration
                    self._explore_directory_deeper(directory, contents)
            except Exception as e:
                self.console.print(
                    f"[red]Error exploring directory {directory}: {str(e)}[/red]"
                )

    def _explore_directory_deeper(self, directory, contents):
        """
        Explore a directory more deeply by examining its contents.
        This helps ensure that important files and subdirectories are not missed.

        Args:
            directory: The directory to explore
            contents: List of items in the directory
        """
        # Check for important files that should be read
        important_extensions = [
            ".py",
            ".js",
            ".ts",
            ".jsx",
            ".tsx",
            ".json",
            ".md",
            ".txt",
            ".html",
            ".css",
        ]
        important_filenames = [
            "README",
            "requirements.txt",
            "package.json",
            "setup.py",
            "config.json",
            ".env",
        ]

        # Find important files to read
        important_files = []
        for item in contents:
            item_path = os.path.join(directory, item)
            if os.path.isfile(item_path):
                # Check if it's an important file by extension or name
                file_ext = os.path.splitext(item)[1].lower()
                if file_ext in important_extensions or any(
                    name.lower() in item.lower() for name in important_filenames
                ):
                    important_files.append(item_path)
            elif os.path.isdir(item_path):
                # Add subdirectory to current_directories
                self.context_manager.current_directories.add(item_path)

        # Read important files (limit to 3 to avoid overwhelming)
        # This part needs to be async if it calls _execute_tool
        # For now, _explore_directory_deeper is synchronous and does not call _execute_tool directly
        # If it were to call an async _execute_tool, this method would need to be async too.
        # The current implementation of reading files is in _check_mentioned_files and _ensure_directories_explored.
        # This _explore_directory_deeper method currently only identifies files and adds subdirs to context.
        # If we want it to *read* files, it must become async and call await self._execute_tool.
        # Let's keep it synchronous for now as it doesn't directly execute tools.
        for file_path in important_files[:3]:
            if file_path not in self.context_manager.current_files:
                self.console.print(
                    f"[yellow]Identified important file (will be read if mentioned or needed): {file_path}[/yellow]"
                )
                # To actively read:
                # tool_use = ToolUseMock("filecontentreadertool", {"file_paths": [file_path]})
                # await self._execute_tool(tool_use) ... and handle history as in _check_mentioned_files
                # For now, just identifying.

    def _display_conversation_info(self):
        """
        Display information about the conversation optimization feature.
        This is shown when users type 'info' in the chat.
        """
        recent_message_count = getattr(Config, "RECENT_MESSAGE_COUNT", 3)

        info_text = f"""
# Conversation Optimization Information

This agent uses an optimized conversation history approach to reduce token usage and improve performance:

- **Full History**: The agent maintains a complete conversation history internally for context tracking and tool execution.
- **Optimized API Calls**: When making API calls to the language model, only system messages and the {recent_message_count} most recent non-system messages are included.
- **Token Savings**: This optimization can significantly reduce token usage for longer conversations, allowing for more efficient operation.

## Current Settings:
- Recent message count: {recent_message_count} (configurable via Config.RECENT_MESSAGE_COUNT)
- Maximum conversation tokens: {Config.MAX_CONVERSATION_TOKENS:,}
- Current token usage: {self.total_tokens_used:,} ({(self.total_tokens_used / Config.MAX_CONVERSATION_TOKENS) * 100:.1f}%)

## Commands:
- Type 'refresh' to reload available tools
- Type 'reset' to clear conversation history
- Type 'info' to display this information
- Type 'quit' to exit
"""

        # Add conversation statistics if available
        if self.conversation_history:
            system_messages = [
                msg for msg in self.conversation_history if msg.get("role") == "system"
            ]
            other_messages = [
                msg for msg in self.conversation_history if msg.get("role") != "system"
            ]
            recent_history = (
                other_messages[-recent_message_count:] if other_messages else []
            )

            info_text += f"""
## Current Conversation Stats:
- Total messages: {len(self.conversation_history)}
- System messages: {len(system_messages)}
- Non-system messages: {len(other_messages)}
- Messages included in API calls: {len(system_messages) + len(recent_history)} ({len(system_messages)} system + {len(recent_history)} recent)
"""

            # Add token savings estimate if significant
            if len(other_messages) > recent_message_count:

                def estimate_tokens(messages):
                    total = 0
                    for msg in messages:
                        content = msg.get("content", "")
                        if content:
                            total += len(content) // 4
                    return total

                full_history_tokens = estimate_tokens(self.conversation_history)
                optimized_tokens = estimate_tokens(system_messages + recent_history)

                if full_history_tokens > 0:
                    savings_percentage = (
                        (full_history_tokens - optimized_tokens) / full_history_tokens
                    ) * 100
                    info_text += f"""
## Estimated Token Savings:
- Full history tokens: ~{full_history_tokens:,}
- Optimized tokens: ~{optimized_tokens:,}
- Savings: ~{savings_percentage:.1f}% ({full_history_tokens - optimized_tokens:,} tokens)
"""

        return info_text

    async def _check_mentioned_files(self):
        """
        Check if any files were mentioned in the conversation but not read.
        This helps ensure that all relevant files are explored within a step.
        """
        # Extract file paths mentioned in the conversation
        mentioned_files = set()
        for message in self.conversation_history:
            if message.get("role") == "assistant" and message.get("content"):
                content = message.get("content", "")
                if isinstance(content, str):
                    # Simple regex to find potential file paths
                    file_matches = re.findall(
                        r"`[^`]*`|\b[\w\-\.\/]+\.(py|js|ts|jsx|tsx|html|css|json|md|txt)\b",
                        content,
                    )
                    for match in file_matches:
                        # Clean up the match
                        file_path = match.strip("`")
                        if os.path.exists(file_path) and os.path.isfile(file_path):
                            mentioned_files.add(file_path)

        # Check which mentioned files haven't been read
        unread_files = mentioned_files - self.context_manager.current_files

        # Read unread files that were mentioned
        for file_path in unread_files:
            self.console.print(
                f"[yellow]File {file_path} was mentioned but not read. Reading...[/yellow]"
            )

            # Create a mock tool use object for reading the file
            class ToolUseMock:
                def __init__(self, name, input_data):
                    self.name = name
                    self.input = input_data

            tool_use = ToolUseMock("filecontentreadertool", {"file_paths": [file_path]})
            await self._execute_tool(tool_use)

            # Add the tool call to conversation history
            tool_call_id = f"auto_read_{file_path}"
            tool_call_message = {
                "role": "assistant",
                "content": None,
                "tool_calls": [
                    {
                        "id": tool_call_id,
                        "type": "function",
                        "function": {
                            "name": "filecontentreadertool",
                            "arguments": json.dumps({"file_paths": [file_path]}),
                        },
                    }
                ],
            }
            self.conversation_history.append(tool_call_message)

            # Instead of appending the full tool result, just append a success message
            self.conversation_history.append(
                {
                    "role": "tool",
                    "tool_call_id": tool_call_id,
                    "name": "filecontentreadertool",
                    "content": "Tool execution successful",
                }
            )

            self.console.print(f"[green]File {file_path} read.[/green]")

            # Add the file to current_files
            self.context_manager.current_files.add(file_path)


class ContextManager:
    """
    Manages context for the LLM_Agent, tracking information about the current
    conversation, files being discussed, and other relevant context.
    """

    def __init__(self):
        self.current_files = set()
        self.current_directories = set()
        self.recent_topics = []
        self.workspace_root = os.getcwd()
        self.report_memory = []

    def get_relevant_context(self) -> dict[str, Any]:
        """
        Get relevant context information for the current conversation.
        """
        return {
            "current_files": list(self.current_files),
            "current_directories": list(self.current_directories),
            "workspace_root": self.workspace_root,
            "recent_topics": self.recent_topics,
        }


# %%
